class Address < ApplicationRecord
  attr_accessor :street_address, :zip_code, :front_end

  GIS_URL = "http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates"
  STATES = %w(AL AK AS AZ AR CA CO CT DE DC FM FL GA GU HI ID IL IN IA KS 
              KY LA ME MH MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND MP 
              OH OK OR PW PA PR RI SC SD TN TX UT VT VI VA WA WV WI WY AE AP AA)
  DIRECTIONS = %w(N E S W NE SE NW SW)
  UNIT_TYPES = %w(APARTMENT APT BASEMENT BSMT BUILDING BLDG DEPARTMENT DEPT 
                  FLOOR FL FRONT FRNT HANGER HNGR KEY KEY LOBBY LBBY LOT LOT 
                  LOWER LOWR OFFICE OFC PENTHOUSE PH PIER PIER REAR REAR ROOM RM 
                  SIDE SIDE SLIP SLIP SPACE SPC STOP STOP SUITE STE TRAILER TRLR 
                  UNIT UNIT UPPER UPPR)
  STREET_TYPES = %w(ALLEE ALLEY ALLY ALY ANEX ANNEX ANNX ANX ARC ARCADE AV AVE AVEN AVENU AVENUE AVN AVNUE BAYOO BAYOU BCH BEACH BEND BND BLF BLUF BLUFF BLUFFS BOT BTM BOTTM BOTTOM BLVD BOUL BOULEVARD BOULV BR BRNCH BRANCH BRDGE BRG BRIDGE BRK BROOK BROOKS BURG BURGS BYP BYPA BYPAS BYPASS BYPS CAMP CP CMP CANYN CANYON CNYN CAPE CPE CAUSEWAY CAUSWA CSWY CEN CENT CENTER CENTR CENTRE CNTER CNTR CTR CENTERS CIR CIRC CIRCL CIRCLE CRCL CRCLE CIRCLES CLF CLIFF CLFS CLIFFS CLB CLUB COMMON COMMONS COR CORNER CORNERS CORS COURSE CRSE COURT CT COURTS CTS COVE CV COVES CREEK CRK CRESCENT CRES CRSENT CRSNT CREST CROSSING CRSSNG XING CROSSROAD CROSSROADS CURVE DALE DL DAM DM DIV DIVIDE DV DVD DR DRIV DRIVE DRV DRIVES EST ESTATE ESTATES ESTS EXP EXPR EXPRESS EXPRESSWAY EXPW EXPY EXT EXTENSION EXTN EXTNSN EXTS FALL FALLS FLS FERRY FRRY FRY FIELD FLD FIELDS FLDS FLAT FLT FLATS FLTS FORD FRD FORDS FOREST FORESTS FRST FORG FORGE FRG FORGES FORK FRK FORKS FRKS FORT FRT FT FREEWAY FREEWY FRWAY FRWY FWY GARDEN GARDN GRDEN GRDN GARDENS GDNS GRDNS GATEWAY GATEWY GATWAY GTWAY GTWY GLEN GLN GLENS GREEN GRN GREENS GROV GROVE GRV GROVES HARB HARBOR HARBR HBR HRBOR HARBORS HAVEN HVN HT HTS HIGHWAY HIGHWY HIWAY HIWY HWAY HWY HILL HL HILLS HLS HLLW HOLLOW HOLLOWS HOLW HOLWS INLT IS ISLAND ISLND ISLANDS ISLNDS ISS ISLE ISLES JCT JCTION JCTN JUNCTION JUNCTN JUNCTON JCTNS JCTS JUNCTIONS KEY KY KEYS KYS KNL KNOL KNOLL KNLS KNOLLS LK LAKE LKS LAKES LAND LANDING LNDG LNDNG LANE LN LGT LIGHT LIGHTS LF LOAF LCK LOCK LCKS LOCKS LDG LDGE LODG LODGE LOOP LOOPS MALL MNR MANOR MANORS MNRS MEADOW MDW MDWS MEADOWS MEDOWS MEWS MILL MILLS MISSN MSSN MOTORWAY MNT MT MOUNT MNTAIN MNTN MOUNTAIN MOUNTIN MTIN MTN MNTNS MOUNTAINS NCK NECK ORCH ORCHARD ORCHRD OVAL OVL OVERPASS PARK PRK PARKS PARKWAY PARKWY PKWAY PKWY PKY PARKWAYS PKWYS PASS PASSAGE PATH PATHS PIKE PIKES PINE PINES PNES PL PLAIN PLN PLAINS PLNS PLAZA PLZ PLZA POINT PT POINTS PTS PORT PRT PORTS PRTS PR PRAIRIE PRR RAD RADIAL RADIEL RADL RAMP RANCH RANCHES RNCH RNCHS RAPID RPD RAPIDS RPDS REST RST RDG RDGE RIDGE RDGS RIDGES RIV RIVER RVR RIVR RD ROAD ROADS RDS ROUTE ROW RUE RUN SHL SHOAL SHLS SHOALS SHOAR SHORE SHR SHOARS SHORES SHRS SKYWAY SPG SPNG SPRING SPRNG SPGS SPNGS SPRINGS SPRNGS SPUR SPURS SQ SQR SQRE SQU SQUARE SQRS SQUARES STA STATION STATN STN STRA STRAV STRAVEN STRAVENUE STRAVN STRVN STRVNUE STREAM STREME STRM STREET STRT ST STR STREETS SMT SUMIT SUMITT SUMMIT TER TERR TERRACE THROUGHWAY TRACE TRACES TRCE TRACK TRACKS TRAK TRK TRKS TRAFFICWAY TRAIL TRAILS TRL TRLS TRAILER TRLR TRLRS TUNEL TUNL TUNLS TUNNEL TUNNELS TUNNL TRNPK TURNPIKE TURNPK UNDERPASS UN UNION UNIONS VALLEY VALLY VLLY VLY VALLEYS VLYS VDCT VIA VIADCT VIADUCT VIEW VW VIEWS VWS VILL VILLAG VILLAGE VILLG VILLIAGE VLG VILLAGES VLGS VILLE VL VIS VIST VISTA VST VSTA WALK WALKS WALL WY WAY WAYS WELL WELLS WLS)

  validates_address :street_address
  validates :city, 
            :state, 
            :house_number, 
            :street_name, 
            :zip_5, 
            presence: true
  validates :street_address, 
            :zip_code,
            presence: true,
            if: :front_end?
  validates :state,
            format: { with: /[A-Za-z]/ }, 
            inclusion: { in: STATES }
  validates :zip_code, 
            length: { in: 5..10 }, 
            format: { with: /\d{5}(-?\d{4})?\z/ },
            allow_blank: true
  validates :house_number, :zip_4, numericality: { only_integer: true }, allow_blank: true
  validates :zip_5, length: { is: 5 }, numericality: { only_integer: true }, allow_blank: true
  validates :zip_4, length: { is: 4 }, numericality: { only_integer: true }, allow_blank: true
  validates :street_predirection, :street_postdirection, inclusion: { in: DIRECTIONS }, allow_blank: true

  def to_s
    [ house_number,
      street_predirection,
      street_name,
      street_type,
      street_postdirection,
      unit_type].compact.join(" ") + " " +
    [ unit_number,
      city,
      state].join(", ") + " #{zip_5}"
  end

  def arc_gis_params
    {
      address: street_address,
      city: city,
      region: state,
      postal: zip_code,
      outFields: "*",
      forStorage: false,
      f: "pjson"
    }.to_query
  end

  def front_end?
    front_end
  end
end
